// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net8StarterAuthApi.Data;

#nullable disable

namespace Net8StarterAuthApi.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AdminRoleUser", b =>
                {
                    b.Property<string>("AdminRolesName")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("admin_roles_name");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("char(36)")
                        .HasColumnName("users_id");

                    b.HasKey("AdminRolesName", "UsersId")
                        .HasName("pk_admin_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_admin_role_user_users_id");

                    b.ToTable("admin_role_user", (string)null);
                });

            modelBuilder.Entity("Net8StarterAuthApi.Models.AdminRole", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("name");

                    b.Property<string>("Description")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("description");

                    b.HasKey("Name")
                        .HasName("pk_admin_roles");

                    b.ToTable("admin_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "sysadmin",
                            Description = "System Admin"
                        },
                        new
                        {
                            Name = "support",
                            Description = "Internal Support"
                        });
                });

            modelBuilder.Entity("Net8StarterAuthApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12d1ab10-aaa6-11ef-9084-ec8f097e5f62"),
                            Email = "a2ron44@gmail.com",
                            FirstName = "Aaron",
                            LastName = "H"
                        });
                });

            modelBuilder.Entity("AdminRoleUser", b =>
                {
                    b.HasOne("Net8StarterAuthApi.Models.AdminRole", null)
                        .WithMany()
                        .HasForeignKey("AdminRolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_role_user_admin_roles_admin_roles_name");

                    b.HasOne("Net8StarterAuthApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_role_user_users_users_id");
                });
#pragma warning restore 612, 618
        }
    }
}
